CREATE DATABASE SQL_CACHE;

USE SQL_CACHE;

DROP TABLE CACHE;
DROP TABLE CLUSTER_CONFIGURATION;
DROP TABLE COMMIT_LOGS;

CREATE TABLE CACHE(
	CACHE_KEY VARCHAR(255) PRIMARY KEY NOT NULL,
	CACHE_VALUE VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP)
	

CREATE TABLE CLUSTER_CONFIGURATION(
    CLUSTER_CONF_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IP VARCHAR(255) NOT NULL,
	PORT INT NOT NULL,
	COMMIT_LOG_ID INT NOT NULL,
	STATUS VARCHAR(255) DEFAULT "ACTIVE",
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP )
	
CREATE TABLE COMMIT_LOGS(
    COMMIT_LOG_ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OPERATION VARCHAR(255) NOT NULL,
	CACHE_KEY VARCHAR(255) NOT NULL,
	CACHE_VALUE VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP)